# SPDX-FileCopyrightText: 2019 Serge Guelton
# SPDX-FileCopyrightText: 2021 ETH Zurich and the NPBench authors
# SPDX-FileCopyrightText: 2022 - 2023 Intel Corporation
#
# SPDX-License-Identifier: BSD-3-Clause

[benchmark]
name = "Arc Distance"

[benchmark.parameters.S]
N = 100000

[benchmark.parameters.M]
N = 1000000

[benchmark.parameters.L]
N = 10000000

[benchmark.parameters.paper]
N = 10000000
