# SPDX-FileCopyrightText: 2017 Nicolas P. Rougier
# SPDX-FileCopyrightText: 2021 ETH Zurich and the NPBench authors
# SPDX-FileCopyrightText: 2022 - 2023 Intel Corporation
#
# SPDX-License-Identifier: BSD-3-Clause

[benchmark]
name = "Mandelbrot2"

[benchmark.parameters.S]
xmin = -2.0
xmax = 0.5
xn = 200
ymin = -1.25
ymax = 1.25
yn = 200
itermax = 40
horizon = 2.0

[benchmark.parameters.M]
xmin = -2.0
xmax = 0.5
xn = 500
ymin = -1.25
ymax = 1.25
yn = 500
itermax = 80
horizon = 2.0

[benchmark.parameters.L]
xmin = -2.25
xmax = 0.75
xn = 1000
ymin = -1.5
ymax = 1.5
yn = 1000
itermax = 100
horizon = 2.0

[benchmark.parameters.paper]
xmin = -2.25
xmax = 0.75
xn = 1000
ymin = -1.25
ymax = 1.25
yn = 1000
itermax = 200
horizon = 2.0
