# SPDX-FileCopyrightText: 2022 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/PyCQA/bandit
    rev: '1.7.0'
    hooks:
    -   id: bandit
        pass_filenames: false
        args: ["-r", "numba_mlir", "-lll"]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.8.0
    hooks:
    -   id: black
        exclude: "versioneer.py|numba_mlir/_version.py"
-   repo: https://github.com/pycqa/flake8
    rev: 3.9.1
    hooks:
    -   id: flake8
-   repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.1.1
    hooks:
    -   id: clang-format
        args: ["-i"]
