# SPDX-FileCopyrightText: 2012-2020 Anaconda, Inc. and others
# SPDX-FileCopyrightText: 2021 ETH Zurich and the NPBench authors
# SPDX-FileCopyrightText: 2022 - 2023 Intel Corporation
#
# SPDX-License-Identifier: BSD-3-Clause

[benchmark]
name = "GoFast"

[benchmark.parameters.S]
N = 2000

[benchmark.parameters.M]
N = 6000

[benchmark.parameters.L]
N = 20000

[benchmark.parameters.paper]
N = 12500
