{% set dpcpp_version = ">=2023.1" %}

package:
    name: numba-mlir
    version: {{ GIT_DESCRIBE_TAG }}

source:
    path: ../..

build:
    number: {{ GIT_DESCRIBE_NUMBER }}
    script_env:
        - LLVM_PATH
        - LEVEL_ZERO_DIR
        - LEVEL_ZERO_VERSION_CHECK_OFF
        - NUMBA_MLIR_USE_SYCL

requirements:
    build:
        - {{ compiler('cxx') }}
        - {{ compiler('dpcpp') }}  >=2023.1, != 2024.0.1, != 2024.0.2  # [not osx]
        - sysroot_linux-64 >=2.17  # [linux]
    host:
        - cmake >=3.23
        - mkl-devel {{ dpcpp_version }}
        - mkl-devel-dpcpp {{ dpcpp_version }}
        - mkl {{ dpcpp_version }}
        - mkl-dpcpp {{ dpcpp_version }}
        - dpcpp-cpp-rt {{ dpcpp_version }}
        - dpcpp_cpp_rt {{ dpcpp_version }}
        - tbb-devel >=2021.6.0
        - level-zero-devel
        - ninja
        - numba >=0.57, <0.59
        - pybind11
        - python
        - setuptools
        - wheel
        - zlib
    run:
        - mkl
        - mkl-dpcpp
        - numba >=0.57, <0.59
        - packaging
        - python
        - tbb >=2021.6.0

test:
    requires:
        - pytest
        - pytest-xdist
        - scikit-learn
        - scipy
    files:
        - run_package_tests.py
    commands:
        - python run_package_tests.py verbose smoke
