package:
    name: numba-mlir
    version: {{ GIT_DESCRIBE_TAG }}

source:
    path: ../..

build:
    number: {{ GIT_DESCRIBE_NUMBER }}
    preserve_egg_dir: True
    script_env:
        - TBB_PATH
        - LLVM_PATH
        - LEVEL_ZERO_DIR
        - LEVEL_ZERO_VERSION_CHECK_OFF

requirements:
    build:
        - python
        - ninja
        - cmake
        - pybind11
        - mkl-devel >=2023.0.0
        - mkl-devel-dpcpp >=2023.0.0
    host:
        - python
        - mkl-devel >=2023.0.0
        - mkl-devel-dpcpp >=2023.0.0
        - setuptools <65.6
        - numba 0.56*
    run:
        - python
        - numba 0.56*
        - packaging
        - mkl >=2023.0.0
        - tbb >=2021.6.0
        - zlib

test:
    requires:
        - pytest
