package:
    name: numba-mlir
    version: {{ GIT_DESCRIBE_TAG }}

source:
    path: ../..

build:
    number: {{ GIT_DESCRIBE_NUMBER }}
    script_env:
        - TBB_PATH
        - LLVM_PATH
        - LEVEL_ZERO_DIR
        - LEVEL_ZERO_VERSION_CHECK_OFF
        - NUMBA_MLIR_USE_SYCL

requirements:
    build:
        - {{ compiler('cxx') }}
        - {{ compiler('dpcpp') }}  >=2023.0  # [not osx]
    host:
        - cmake >=3.23
        - mkl-devel >=2023.0
        - mkl-devel-dpcpp >=2023.0
        - ninja
        - numba =0.57
        - pybind11
        - python
        - setuptools
        - wheel
        - zlib
    run:
        - mkl >=2023.0
        - mkl-dpcpp >=2023.0
        - numba =0.57
        - packaging
        - python
        - tbb >=2021.6.0

test:
    requires:
        - pytest
