package:
    name: numba-mlir
    version: 0.0

source:
    path: ../..

build:
    number: 0
    script_env:
        - TBB_PATH
        - LLVM_PATH
        - LEVEL_ZERO_DIR
        - LEVEL_ZERO_VERSION_CHECK_OFF

requirements:
    build:
        - ninja
        - cmake
        - pybind11
        - mkl-devel-dpcpp
    host:
        - python
        - setuptools
        - numba 0.56*
        - wheel
    run:
        - python
        - numba 0.56*
        - packaging

test:
    requires:
        - pytest
