# SPDX-FileCopyrightText: 2010-2016 Ohio State University
# SPDX-FileCopyrightText: 2021 ETH Zurich and the NPBench authors
# SPDX-FileCopyrightText: 2022 - 2023 Intel Corporation
#
# SPDX-License-Identifier: BSD-3-Clause

[benchmark]
name = "Vector Multiplication and Matrix Addition"

[benchmark.parameters.S]
N = 1000

[benchmark.parameters.M]
N = 3000

[benchmark.parameters.L]
N = 10000

[benchmark.parameters.paper]
N = 8000
