# SPDX-FileCopyrightText: 2014-2021 ETH Zurich
# SPDX-FileCopyrightText: 2007 Free Software Foundation, Inc. <https://fsf.org/>
# SPDX-FileCopyrightText: 2021 ETH Zurich and the NPBench authors
# SPDX-FileCopyrightText: 2022 - 2023 Intel Corporation
#
# SPDX-License-Identifier: GPL-3.0-or-later

[benchmark]
name = "Horizontal Diffusion"

[benchmark.parameters.S]
I = 64
J = 64
K = 60

[benchmark.parameters.M]
I = 128
J = 128
K = 160

[benchmark.parameters.L]
I = 384
J = 384
K = 160

[benchmark.parameters.paper]
I = 256
J = 256
K = 160
