# SPDX-FileCopyrightText: 2010-2016 Ohio State University
# SPDX-FileCopyrightText: 2021 ETH Zurich and the NPBench authors
# SPDX-FileCopyrightText: 2022 - 2023 Intel Corporation
#
# SPDX-License-Identifier: BSD-3-Clause

[benchmark]
name = "Floyd-Warshall"

[benchmark.parameters.S]
N = 200

[benchmark.parameters.M]
N = 400

[benchmark.parameters.L]
N = 850

[benchmark.parameters.paper]
N = 2800
