# SPDX-FileCopyrightText: 2010-2016 Ohio State University
# SPDX-FileCopyrightText: 2021 ETH Zurich and the NPBench authors
# SPDX-FileCopyrightText: 2022 - 2023 Intel Corporation
#
# SPDX-License-Identifier: BSD-3-Clause

[benchmark]
name = "3 Matrix Multiplications"

[benchmark.parameters.S]
NI = 800
NJ = 8500
NK = 900
NL = 950
NM = 1000

[benchmark.parameters.M]
NI = 2000
NJ = 2200
NK = 2400
NL = 2600
NM = 2800

[benchmark.parameters.L]
NI = 5500
NJ = 6000
NK = 6500
NL = 7000
NM = 7500

[benchmark.parameters.paper]
NI = 3200
NJ = 3600
NK = 4000
NL = 4400
NM = 4800
