# SPDX-FileCopyrightText: 2010-2016 Ohio State University
# SPDX-FileCopyrightText: 2021 ETH Zurich and the NPBench authors
# SPDX-FileCopyrightText: 2022 - 2023 Intel Corporation
#
# SPDX-License-Identifier: BSD-3-Clause

[benchmark]
name = "Cholesky Decomposition"

[benchmark.parameters.S]
N = 100

[benchmark.parameters.M]
N = 300

[benchmark.parameters.L]
N = 900

[benchmark.parameters.paper]
N = 2000
