# SPDX-FileCopyrightText: 2010-2016 Ohio State University
# SPDX-FileCopyrightText: 2021 ETH Zurich and the NPBench authors
# SPDX-FileCopyrightText: 2022 - 2023 Intel Corporation
#
# SPDX-License-Identifier: BSD-3-Clause

[benchmark]
name = "Gram-Schmidt decomposition"

[benchmark.parameters.S]
M = 70
N = 60

[benchmark.parameters.M]
M = 220
N = 180

[benchmark.parameters.L]
M = 600
N = 500

[benchmark.parameters.paper]
M = 240
N = 200
