# SPDX-FileCopyrightText: 2010-2016 Ohio State University
# SPDX-FileCopyrightText: 2021 ETH Zurich and the NPBench authors
# SPDX-FileCopyrightText: 2022 - 2023 Intel Corporation
#
# SPDX-License-Identifier: BSD-3-Clause

[benchmark]
name = "Symmetric rank-k operations"

[benchmark.parameters.S]
M = 50
N = 70

[benchmark.parameters.M]
M = 150
N = 200

[benchmark.parameters.L]
M = 500
N = 600

[benchmark.parameters.paper]
M = 1000
N = 1200
