# SPDX-FileCopyrightText: 2010-2016 Ohio State University
# SPDX-FileCopyrightText: 2021 ETH Zurich and the NPBench authors
# SPDX-FileCopyrightText: 2022 - 2023 Intel Corporation
#
# SPDX-License-Identifier: BSD-3-Clause

[benchmark]
name = "Triangular solver"

[benchmark.parameters.S]
N = 2000

[benchmark.parameters.M]
N = 5000

[benchmark.parameters.L]
N = 14000

[benchmark.parameters.paper]
N = 16000
